### ISSUE TITLE
How to make a decision weather in Object detected or not ?

### ISSUE THREAD

**Issue by diaz9557** [michaeltroger/feature-matching-native-android#1]
First of all Thx for providing this repo. 
I have several questions .
1. How to make a decision weather in Object detected or not ? I have to show the user if object found or not accurately . Found or not found?
2. I have tested it with several templates it only works on some. As per my need i need to scan the rigid object like a toy or something like laughing buddha for example.
 Will it work in that case ? If not then which approach should i follow ?

Please respond i am stuck here for days .

**Comment by michaeltroger** [comment]
Hi!
You're welcome.
I didn't engage with OpenCV for a longer period now.
As for the object detected or not question, my suggestion is to look into `native_opencv.cpp`. There the condition `if (!good_matches.empty())` is true if there was a match. Currently there is no "else" - i.e. in case there is no match nothing is done.

The application uses OpenCV as computer vision algorithm and so I can't help you with your second question as the detection quality highly depends on this library. There are however some things you can try to improve detection like a higher camera resolution or doing some preprocessing to clean the camera image upfront. 

Please understand that I currently don't have any time resources available to give further support. I hope I could still help a little!

**Comment by diaz9557** [comment]
Thanks anyway . I wanna share the solution i have used. Actually OpenCV did not workout well for me cause i do not have enough time to spend on it to understand Image processing. 
However for template matching decision link below helped me a lot . There are 4 conditions listed try to implements any one . For me the 3rd one worked with much better result .

  [https://stackoverflow.com/a/42515173/7995966](check_homography)
